name: release

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
    branches:
      - main

  workflow_dispatch:

concurrency: 
  group: release # only 1 release at a time

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

      - name: env - better defaulting of env vars;
        id: env
        run: |

            LARGE_FILE_REPOSITORY="${{ secrets.LARGE_FILE_REPOSITORY }}"
            if [[ -z "$LARGE_FILE_REPOSITORY" ]]; then
              LARGE_FILE_REPOSITORY="PortsMaster/PortMaster-Hosting"
            fi
            echo "LARGE_FILE_REPOSITORY=$LARGE_FILE_REPOSITORY" >> $GITHUB_OUTPUT

            LARGE_FILE_TAG="${{ secrets.LARGE_FILE_TAG }}"
            if [[ -z "$LARGE_FILE_TAG" ]]; then
              LARGE_FILE_TAG="large-files"
            fi
            echo "LARGE_FILE_TAG=$LARGE_FILE_TAG" >> $GITHUB_OUTPUT

            RELEASE_REPO="${{ secrets.RELEASE_REPO }}"
            if [[ -z "$RELEASE_REPO" ]]; then
              RELEASE_REPO="PortMaster-Releases"
            fi
            echo "RELEASE_REPO=$RELEASE_REPO" >> $GITHUB_OUTPUT

            RELEASE_ORG="${{ secrets.RELEASE_ORG }}"
            if [[ -z "$RELEASE_ORG" ]]; then
              RELEASE_ORG="PortsMaster"
            fi
            echo "RELEASE_ORG=$RELEASE_ORG" >> $GITHUB_OUTPUT

      - uses: hmarr/debug-action@v2
        name: "debug: ${{github.event_name}}"
     
      - uses: actions/checkout@v2
 
      - uses: robinraju/release-downloader@v1.2
        with:
          repository: "${{ steps.env.outputs.LARGE_FILE_REPOSITORY}}"
          tag: "${{steps.env.outputs.LARGE_FILE_TAG}}"
          fileName: "*"

      - name: Get release name for artifacts
        id: date
        run: |
            echo "date=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_OUTPUT
      - name: Create PortMaster zip from PortMaster Folder
        id: portmaster-zip
        run: |
          zip -9 -r ./PortMaster.zip PortMaster/
      - name: Create images zip from images Folder
        id: images-zip
        run: |
          find images \( -iname '*.jpg' -o  -iname '*.png' \) -exec touch -d '2021-01-01 00:00:00' {} \;
          find images \( -iname '*.jpg' -o  -iname '*.png' \) -exec chmod 644 {} \;
          find images \( -iname '*.jpg' -o  -iname '*.png' \) | sort | TZ=UTC zip -qX images.zip -@
      - name: Create md5 hashes
        id: md5
        run: |
            for file in *.zip *.squashfs; do
              if [ ! -f "$file" ]; then
                continue
              fi
              echo "file: $file"
              md5sum "$file" | cut -f1 -d' ' > "$file.md5"
            done
      - name: "Prepare Release"
        uses: ncipollo/release-action@v1
        with:
          tag: "${{steps.date.outputs.date}}"
          allowUpdates: true
          draft: true
          prerelease: false
          replacesArtifacts: false
          omitNameDuringUpdate: true
          artifacts: "ports.md, *.zip, version, *.squashfs, *.md5"
          token: ${{ secrets.PORTMASTER_RELEASE_TOKEN }}
          repo: ${{ steps.env.outputs.RELEASE_REPO }}
          owner: ${{ steps.env.outputs.RELEASE_ORG }}
      - name: "Publish Release"
        uses: ncipollo/release-action@v1
        with:
          tag: "${{steps.date.outputs.date}}"
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          allowUpdates: true
          draft: false
          prerelease: false
          token: ${{ secrets.PORTMASTER_RELEASE_TOKEN }}
          repo: ${{ steps.env.outputs.RELEASE_REPO }}
          owner: ${{ steps.env.outputs.RELEASE_ORG }}
      - name: Release Info
        id: info
        run: |
          echo "Published release: ${{steps.date.outputs.date}} to: https://github.com/${{ steps.env.outputs.RELEASE_ORG}}/${{ steps.env.outputs.RELEASE_REPO}}"
